"""update_api_request_logs

Revision ID: 3807c7b7b2ed
Revises: f5e84031d10b
Create Date: 2026-08-05 00:38:46.751594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3807c7b7b2ed'
down_revision: Union[str, None] = 'f5e84031d10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_request_logs', sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('api_request_logs', sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('api_request_logs', sa.Column('message', sa.String(), nullable=True))
    op.create_index(op.f('ix_reports_geom'), 'reports', ['geom'], unique=False)
    op.create_index(op.f('ix_safe_points_geom'), 'safe_points', ['geom'], unique=False)
    op.alter_column('user_preferences', 'priority_main_road',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_preferences', 'auto_share_sos_to_contacts',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_preferences', 'alert_radius_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'alert_radius_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_preferences', 'auto_share_sos_to_contacts',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_preferences', 'priority_main_road',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_safe_points_geom'), table_name='safe_points')
    op.drop_index(op.f('ix_reports_geom'), table_name='reports')
    op.drop_column('api_request_logs', 'message')
    op.drop_column('api_request_logs', 'request_body')
    op.drop_column('api_request_logs', 'query_params')

    # ### end Alembic commands ###
